# Generated by Django 5.0 on 2023-12-13 22:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jogador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Insira o nome do jogador.', max_length=200)),
                ('numeroDaCamisa', models.CharField(help_text='Insira o número da camisa.', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Posicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Insira a posição do jogador.', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Treinador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Insira o nome do treinador.', max_length=200)),
                ('idade', models.CharField(help_text='Insira a idade do treinador.', max_length=200)),
                ('email', models.CharField(help_text='Insira o e-mail do treinador.', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='ID único para partida dentro do histórico de partidas.', primary_key=True, serialize=False)),
                ('adversario', models.CharField(max_length=200)),
                ('dataHora', models.DateField(blank=True, null=True)),
                ('jogador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.jogador')),
            ],
        ),
        migrations.AddField(
            model_name='jogador',
            name='posicao',
            field=models.ManyToManyField(help_text='Insira a posição do jogador.', to='catalog.posicao'),
        ),
        migrations.AddField(
            model_name='jogador',
            name='treinador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.treinador'),
        ),
    ]
