# Generated by Django 4.2.6 on 2023-12-18 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_remove_partida_jogador_partida_local'),
    ]

    operations = [
        migrations.AddField(
            model_name='partida',
            name='placar',
            field=models.CharField(blank=True, help_text='Insira o placar da partida.', max_length=200),
        ),
        migrations.AlterField(
            model_name='partida',
            name='adversario',
            field=models.CharField(help_text='Insira o nome do time adversário.', max_length=200),
        ),
    ]
